-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 17:49:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EF` DEFAULT CHARACTER SET utf8 ;
USE `EF` ;

-- -----------------------------------------------------
-- Table `EF`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Cliente` (
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Parametros` (
  `idParametros` INT NOT NULL,
  PRIMARY KEY (`idParametros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Bolsa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Bolsa` (
  `idBolsa` INT NOT NULL,
  PRIMARY KEY (`idBolsa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `Parametros_idParametros` INT NOT NULL,
  `Bolsa_idBolsa` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Parametros1_idx` (`Parametros_idParametros` ASC),
  INDEX `fk_Sucursal_Bolsa1_idx` (`Bolsa_idBolsa` ASC),
  CONSTRAINT `fk_Sucursal_Parametros1`
    FOREIGN KEY (`Parametros_idParametros`)
    REFERENCES `EF`.`Parametros` (`idParametros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Bolsa1`
    FOREIGN KEY (`Bolsa_idBolsa`)
    REFERENCES `EF`.`Bolsa` (`idBolsa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Empleado_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `EF`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Contrato` (
  `idContrato` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idContrato`),
  INDEX `fk_Contrato_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Contrato_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Contrato_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `EF`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `EF`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Prenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Prenda` (
  `idPrenda` INT NOT NULL,
  `Contrato_idContrato` INT NOT NULL,
  PRIMARY KEY (`idPrenda`),
  INDEX `fk_Prenda_Contrato1_idx` (`Contrato_idContrato` ASC),
  CONSTRAINT `fk_Prenda_Contrato1`
    FOREIGN KEY (`Contrato_idContrato`)
    REFERENCES `EF`.`Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Artículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Artículo` (
  `idArtículo` INT NOT NULL,
  PRIMARY KEY (`idArtículo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Venta` (
  `idVenta` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Venta_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `EF`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Apartado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Apartado` (
  `idApartado` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idApartado`),
  INDEX `fk_Apartado_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Apartado_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `EF`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Foto_Prenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Foto_Prenda` (
  `idFoto_Prenda` INT NOT NULL,
  `Prenda_idPrenda` INT NOT NULL,
  PRIMARY KEY (`idFoto_Prenda`),
  INDEX `fk_Foto_Prenda_Prenda1_idx` (`Prenda_idPrenda` ASC),
  CONSTRAINT `fk_Foto_Prenda_Prenda1`
    FOREIGN KEY (`Prenda_idPrenda`)
    REFERENCES `EF`.`Prenda` (`idPrenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Foto_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Foto_Cliente` (
  `idFoto_Cliente` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idFoto_Cliente`),
  INDEX `fk_Foto_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Foto_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `EF`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Foto_Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Foto_Articulo` (
  `idFoto_Articulo` INT NOT NULL,
  `Artículo_idArtículo` INT NOT NULL,
  PRIMARY KEY (`idFoto_Articulo`),
  INDEX `fk_Foto_Articulo_Artículo1_idx` (`Artículo_idArtículo` ASC),
  CONSTRAINT `fk_Foto_Articulo_Artículo1`
    FOREIGN KEY (`Artículo_idArtículo`)
    REFERENCES `EF`.`Artículo` (`idArtículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Artículo_has_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Artículo_has_Venta` (
  `Artículo_idArtículo` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  PRIMARY KEY (`Artículo_idArtículo`, `Venta_idVenta`),
  INDEX `fk_Artículo_has_Venta_Venta1_idx` (`Venta_idVenta` ASC),
  INDEX `fk_Artículo_has_Venta_Artículo1_idx` (`Artículo_idArtículo` ASC),
  CONSTRAINT `fk_Artículo_has_Venta_Artículo1`
    FOREIGN KEY (`Artículo_idArtículo`)
    REFERENCES `EF`.`Artículo` (`idArtículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artículo_has_Venta_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `EF`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EF`.`Artículo_has_Apartado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EF`.`Artículo_has_Apartado` (
  `Artículo_idArtículo` INT NOT NULL,
  `Apartado_idApartado` INT NOT NULL,
  PRIMARY KEY (`Artículo_idArtículo`, `Apartado_idApartado`),
  INDEX `fk_Artículo_has_Apartado_Apartado1_idx` (`Apartado_idApartado` ASC),
  INDEX `fk_Artículo_has_Apartado_Artículo1_idx` (`Artículo_idArtículo` ASC),
  CONSTRAINT `fk_Artículo_has_Apartado_Artículo1`
    FOREIGN KEY (`Artículo_idArtículo`)
    REFERENCES `EF`.`Artículo` (`idArtículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artículo_has_Apartado_Apartado1`
    FOREIGN KEY (`Apartado_idApartado`)
    REFERENCES `EF`.`Apartado` (`idApartado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
